### ISSUE TITLE
Inconsistent categorization of "people of wp" posts

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-news-2021#133]
_( this is a content issue, not a dev one, but i wanted to get it tracked )_

#108 and #112 updated the template to use the `people-of-wordpress` tag, instead of the `interviews` category. the posts don't consistently use either of those, though. there's also the `heropress` category.

* https://wordpress.org/news/wp-admin/edit-tags.php?taxonomy=post_tag&post_type=post&s=people
* https://wordpress.org/news/wp-admin/edit.php?s=people&post_status=all&post_type=post&action=-1&m=0&cat=0&paged=1&action2=-1

the `people-of-wordpress` tag is probably the most appropriate for this template part, so we should probably just ask the authors to update the posts to use that.

**Comment by tellyworth** [comment]
+1 for that, PoW seems like the obvious tag to use.

**Comment by dd32** [comment]
I've updated posts to all use the People-of-WordPress tag.

The People of WordPress template however links to `category/community/` for all people - should that be updated to `tags/people-of-wordpress/`?

The HeroPress category has been removed (per #146)

**Comment by ryelle** [comment]
It was requested that "See All People" link to Community here: https://github.com/WordPress/wporg-news-2021/issues/266. Previously it _was_ linking to the People of WordPress tag. See also #203 and https://github.com/WordPress/wporg-news-2021/issues/115#issuecomment-993745600

The confusion here might just be because we know how the templates work — maybe it's not a problem that this homepage section shows posts from the People of WordPress tag, then links off to the Community category? If we switched the home section to show Community posts, it's more than just people. @beafialho Any thoughts here?

**Comment by beafialho** [comment]
> The confusion here might just be because we know how the templates work — maybe it's not a problem that this homepage section shows posts from the People of WordPress tag, then links off to the Community category? If we switched the home section to show Community posts, it's more than just people. @beafialho Any thoughts here?

I think it would be better if the homepage section shows posts from the People of WordPress tag, and links off to the Community category. Ideally, all that appears in the homepage are posts about the people.

**Comment by ryelle** [comment]
In that case, I think we're all set with this issue since @dd32 updated the content, and the current behavior on the site is correct. 👍🏻
