### ISSUE TITLE
Quote Styles: Never use bold + left-align all quotes

### ISSUE THREAD

**Issue by beafialho** [WordPress/wporg-news-2021#140]
I noticed some posts Headings and Quotes, which are meant to use `EB Garamond Regular`, appear in `Bold`. This was perhaps defined by post authors when writing their posts, but it would be great if we could keep this from happening. 

Serif fonts should be carefully dealt with especially when in `Bold`, otherwise they'll contribute to create extra noise to the page and decrease readability. A lot of places in these posts have text in `Bold`.

So my question is: is there a way to make Headings and Quotes use `EB Garamond Regular` only?

**Comment by tellyworth** [comment]
Related: #164

**Comment by tellyworth** [comment]
What needs to happen in order to turn this from a question into something actionable? Would #164 solve it?

**Comment by ryelle** [comment]
I think some examples of where this is happening would help, to see if it's a style issue or a content issue.

For example, these quotes uses multiple `strong` tags — in the first quote it's intentional, but the second is probably a bug, so I'd call that a content issue (the content should be updated). On the other hand, if we _never_ want bold inside quotes, maybe we need a css rule that says `blockquote strong { font-weight: 400 }`; it would strip the bold from both places.

<img width="700" alt="Screen Shot 2022-01-13 at 10 05 57 AM" src="https://user-images.githubusercontent.com/541093/149355244-2a75c620-7e30-4612-a40c-7176978c1feb.png">

<img width="747" alt="Screen Shot 2022-01-13 at 10 02 19 AM" src="https://user-images.githubusercontent.com/541093/149354590-6a1f4618-342f-4507-b811-0d2dbc5aca7e.png">

**Comment by beafialho** [comment]
Thanks for your input @ryelle!

Since the quote styles are quite differentiating from the content, I wouldn't mind using the css rule you suggest to _never_ have bold on quotes. Let's go ahead with that.

Another question that comes up from looking at your screenshots is: can we use a similar rule to force [all quote styles](https://www.figma.com/file/O9I8Jl7kaUMTX39LlRGbGO/News-Page?node-id=4764%3A24492) to be left-aligned? That was the original intention of the design that I didn't explain and now see that having a vertical line on the left with a centered quote doesn't work that well.

**Comment by ryelle** [comment]
> Another question that comes up from looking at your screenshots is: can we use a similar rule to force all quote styles to be left-aligned? That was the original intention of the design that I didn't explain and now see that having a vertical line on the left with a centered quote doesn't work that well.

Could we remove the line on centered quotes instead? I think it would be unexpected for an editor to center a quote and have it not work.

**Comment by beafialho** [comment]
> I think it would be unexpected for an editor to center a quote and have it not work.

The problem isn't the line, it's the fact that centered quotes don't look harmonious in these posts layouts. I agree that it would be unexpected but they'd soon realize it would just look good in the editor, not on the front-end. By having quotes left-aligned we ensure no posts look bad.

**Comment by kellychoffman** [comment]
+1 to unbolding + left aligning

**Comment by ryelle** [comment]
This needs to apply to the pullquote block too.
