### ISSUE TITLE
Local Nav Bar: Rearrange Categories

### ISSUE THREAD

**Issue by beafialho** [WordPress/wporg-news-2021#146]
In the test site, this menu is arranged differently than in both the site and the mockup. Here, it seems to be organized alphabetically.

<img width="1451" alt="Captura de ecrã 2022-01-04, às 15 40 56" src="https://user-images.githubusercontent.com/65220155/148089788-3fc02028-dd6c-492a-9d19-f6a79a5e8bd5.png">

I suggest we organize items by relevance (in the mockup the number of posts in each category was taken in consideration). In the case of "Podcast" we can place it right after "Events", since it's a category we want to highlight.

<img width="1239" alt="Captura de ecrã 2022-01-04, às 16 23 32" src="https://user-images.githubusercontent.com/65220155/148090838-2b7935c9-0cd4-4a42-8185-303b1ba8b8d5.png">

I believe this is critical for the initial launch, since it can create confusion for users navigating Categories having them be rearranged often, but I look forward to hear your thoughts.

cc: @kellychoffman

**Comment by iandunn** [comment]
I agree it'd be bad to change the order post-launch 👍🏻 

The current site makes the order obvious by adding the number of posts after each category name, how do you think removing it will affect visitors? I worry it'll feel confusing or random to folks, and force them to [read instead of skim](https://uxmyths.com/post/647473628/myth-people-read-on-the-web). I don't feel strongly, though.

If the goal is to highlight certain items, what do you think about keeping the alphabetical list, but also adding a "Feature Categories" section above it? This is a very rough sketch of what I'm trying to say:

<img width="1257" alt="Screen Shot 2022-01-04 at 9 03 13 AM" src="https://user-images.githubusercontent.com/484068/148096002-66fe298e-de9a-4a93-84b2-c397950ac827.png">

Regardless, I can see it making sense to put "Uncategorized" last.

**Comment by beafialho** [comment]
> The current site makes the order obvious by adding the number of posts after each category name, how do you think removing it will affect visitors? I worry it'll feel confusing or random to folks, and force them to read instead of skim. I don't feel strongly, though.

Removing the number of posts will definitely reduce the noise in this case. It's also different seeing a list of categories in the sidebar and having a clickable nav bar with the list. In the latter context, items are instantly easier to browse.

> If the goal is to highlight certain items, what do you think about keeping the alphabetical list

What's the benefit in keeping the alphabetical list, in your point of view? I don't see the logic in the first item being "Awards" and "WordCamp" being almost last, for instance. It makes more sense to me to organize items by number of posts. 

> but also adding a "Feature Categories" section above it? This is a very rough sketch of what I'm trying to say:

On the same note as above regarding noise, I'd avoid adding any more elements to this section.

**Comment by iandunn** [comment]
> Removing the number of posts will definitely reduce the noise

I definitely agree it's less cluttered, but the numbers feel more like important info to me than noise. The cost of removing them might be greater than the benefit.

> What's the benefit in keeping the alphabetical list

For me, if I understand how the menu is sorted, then I can more easily navigate it. If I know it's alphabetical, then I can just skip to the middle or end of the list based on the category name. If it's by # of posts, then I can do something similar if I'm familiar enough with the content. It might also help folks memorize the locations, since there's an obvious rhyme and reason, but I haven't researched that.

Even in the cases where it doesn't help me navigate faster, understanding feels better to me than ambiguity.

> I don't see the logic in the first item being "Awards" and "WordCamp" being almost last

Yeah, that's a great point, and definitely a downside to alphabetical.

I don't think it's a big deal either way.

**Comment by beafialho** [comment]
> Even in the cases where it doesn't help me navigate faster, understanding feels better to me than ambiguity.

Yes, I definitely see what you mean 👍 

Both options work and make sense to me, with a preference for organising them by number of posts/relevance. In any case, I think we should place "Uncategorized" as last.

I'd love to know @kellychoffman's thoughts.

**Comment by kellychoffman** [comment]
> organize items by relevance (in the mockup the number of posts in each category was taken in consideration).

Let's do this for launch.

**Comment by dd32** [comment]
Unfortunately WordPress doesn't offer a way to sort categories natively, https://wordpress.org/plugins/taxonomy-terms-order/ is a popular plugin which does it - through the addition of a column to the `terms` table, all the other plugins I see do the same thing. However, I don't think this solves the problem.

The Categories block offered by Gutenberg additionally doesn't allow sorting categories in any way other than alphabetical ascending order. A frontend filter to `get_terms_args` to set `orderby=count&order=DESC` works, but Uncategorized still won't show last without more filters. but also then...

The News blog (not the test news blog) has a long list of categories which are not included in these mockups, that are probably not ideal to include here.

Without just deleting the old categories, I think the cleanest option here is to add some more clarification here - specifically, **what** should the category dropdown show?

I'm thinking it might be sanest to replace the category block with a menu block with statically defined categories.
_edit:_ Another option would be to keep the category block, and just statically define the list of slugs in a filter that should be included into the menu, with the order set there. Still requires PHP though, and I struggle to see the benefit over a static menu other than not having to deal with style changes.

Here's a screenshot of the categories on the w.org/news/ blog in post-count descending order:
<img width="506" alt="Screen Shot 2022-01-21 at 2 15 05 pm" src="https://user-images.githubusercontent.com/767313/150464964-a5a13889-c15b-4320-99e2-11886f5e71e2.png">

**Comment by jeffpaul** [comment]
Alpha sort is, frankly, the only ordering that doesn't break my brain when viewing this super chunky dropdown.

**Comment by dd32** [comment]
Noting this comment from @beafialho - https://github.com/WordPress/wporg-news-2021/pull/243#issuecomment-1022145519

Specifically:
 - Addition of an `All Posts` "category" at the start.
 - Deletion/Rearranging of a bunch of older categories.
 - Hiding some other categories.

The categories block doesn't allow for adding an All Posts item, and won't fit with the CSS in #227. 
The categories block doesn't allow for skipping/excluding certain categories, other than excluding child categories.

I'm going to see about making some of these Categorization changes and cleaning up.

**Comment by dd32** [comment]
I've
 - Removed Focus (2 posts, 2003 and 2018. Assigned to General)
 - Removed Themes (2 posts; 2010 and 2021, former was a Community post, latter better fit Development)
 - Removed Widgets (2 posts; 2006 and 2009, posts better fit Development)
 - Removed Wrapup (2posts; 2017 and 2021, posts better fit their other Cats: Events / General)
 - Removed Hosting (3 posts; 2004, 2010, and 2011. These were PHP requirement announcement changes, already in General.)
 - Removed Cousins (4 posts; 2010/2011; Android + BuddyPress related posts; added the Cousins tag.)
 - Merged User Interface into Design
 - Removed Switchers (9 posts; 2004; "Make the Switch to WordPress" related posts, Tagged as Switchers, all were Development/General categories)
 - Moved Newsletter (& by extension it's child Docs project) to be a child/grand-child of General. Newsletter had too much that didn't fit other categories, and child categories are hidden.
 - Removed HeroPress (and put some in Community because they got missed, and tagged all people as #people-of-wordpress; See #133).  Removing HeroPress felt odd; but it was duplicating the people-of-wordpress tag & the Interview/Community categories.

That's reduced the number of items in the menu significantly.

**Comment by beafialho** [comment]
Thank you @dd32, can I see these changes on `trunk` when testing locally? I still see "Heropress" in the menu. 

Also, I just noticed we don't currently have "All Posts" in the categories dropdown and even though I know it's not a category, it's quite an important link to have. Can we add it there?

**Comment by coreymckrill** [comment]
@beafialho These changes are to content in the database on production, so they won't appear locally. The local content is from an export of the production site a few months ago, and it was a bugger to get it into a state that was safe for committing to a public repo, so it'd be better if we didn't have to refresh it right now.

**Comment by beafialho** [comment]
> These changes are to content in the database on production, so they won't appear locally. The local content is from an export of the production site a few months ago, and it was a bugger to get it into a state that was safe for committing to a public repo, so it'd be better if we didn't have to refresh it right now.

Thanks @coreymckrill, no problem then. I just wanted to check why I wasn't seeing it.
