### ISSUE TITLE
"See All People" button is missing on the right. Here's what it should look like:

### ISSUE THREAD

**Issue by tellyworth** [WordPress/wporg-news-2021#168]
Here's what it should look like:
<img width="1294" alt="Captura de ecrã 2022-01-04, às 11 12 50" src="https://user-images.githubusercontent.com/65220155/148052516-bc55f8b8-0f21-478f-9e03-0e49d7862d9f.png">

**Comment by apeatling** [comment]
@tellyworth This looks to be because there are only 5 total people and the "See all people" is a pagination link. Once another is added it appears:

<img width="1437" alt="Screen Shot 2022-01-11 at 1 22 32 PM" src="https://user-images.githubusercontent.com/1464705/149023704-fe54b2e8-8f64-466c-927e-c952b38e7229.png">

I'll look at a z-index fix.
