### ISSUE TITLE
Global nav bar should stick to the top of the screen when we scroll, both when menus are open or when they're not

### ISSUE THREAD

**Issue by tellyworth** [WordPress/wporg-news-2021#181]
https://user-images.githubusercontent.com/65220155/148379532-7414aa72-35f4-4290-a255-ebda19f78d2a.MP4

https://user-images.githubusercontent.com/65220155/148379924-ed8f98b8-b748-4a4f-92f5-b2ceb48b635f.MP4

**Comment by MaggieCabrera** [comment]
@tellyworth the header has been made "non-sticky" intentionally according to the [comments in the code](https://github.com/WordPress/wporg-news-2021/blob/0d221da24e7f0c379584363503c2052a753a2597/source/wp-content/themes/wporg-news-2021/sass/components/_site-header.scss#L5), because there's less real estate on a phone. Should we make it sticky regardless of that?

**Comment by shaunandrews** [comment]
As Maggie states, the header isn't sticky on mobile, and will continue to be "not-sticky" with the move to flex-box in #178; We _could_ have the headers "stick" on small displays, but this will introduce scrolling issues with the category menu since it will require its own scrolling; We'd then have to disable the page scrolling to avoid having multiple scrollable areas at once.

Perhaps @beafialho can chime in with her thoughts.

**Comment by beafialho** [comment]
> Perhaps @beafialho can chime in with her thoughts.

I believe the ideal solution would be to have the Global Nav's height reduced on scroll in order for it to take up less screen space. Instead of the designed `104px`, it would reduce to `60px`. In such a large site like WordPress.org having these two nav bars sticked to the top seems necessary to me, as it becomes way easier to navigate across the site and the categories. If to achieve that, we need to adjust sizes, we should do so.

<img width="317" alt="Captura de ecrã 2022-01-17, às 17 54 44" src="https://user-images.githubusercontent.com/65220155/149818081-65150670-0937-4c1c-a4ca-3a991086e981.png">

cc: @kellychoffman

**Comment by ryelle** [comment]
Given the community pushback on the sticky header, do we still want this to be sticky on phones too?

**Comment by beafialho** [comment]
Another suggestion to solve the issues raised by the community would be to keep the global nav bar sticky in a possibly even smaller height than `60px` but not the local nav bar. However, if it's an overall unwelcome idea, I'm ok with abandoning the idea of the sticky header on mobile.

**Comment by ryelle** [comment]
The changes in https://github.com/WordPress/wporg-mu-plugins/pull/121 reduce the mobile menu down to 60px tall.

I think we need a final answer on whether the mobile menu will be sticky, with or without the local nav.

**Comment by kellychoffman** [comment]
Let's unstick.

**Comment by ryelle** [comment]
Then we can close this issue, since that's how it works now. Thanks!
