### ISSUE TITLE
Implement design for All Posts archive

### ISSUE THREAD

**Issue by coreymckrill** [WordPress/wporg-news-2021#22]
![all-posts](https://user-images.githubusercontent.com/916023/130859332-374b9471-c2bb-4251-b897-420744c7583b.jpg)

**Comment by beafialho** [comment]
Because the functionality to "Load More Posts" at the bottom of the screen is from Jetpack’s Infinite Scroll module, an alternative would be to have “Older Posts” / “Newer Posts”, as exemplified [here](https://www.figma.com/file/O9I8Jl7kaUMTX39LlRGbGO/News-Page?node-id=7745%3A32376).

In pages with a center-aligned listing, the pagination would be centered:

<img width="961" alt="Captura de ecrã 2021-09-24, às 17 49 54" src="https://user-images.githubusercontent.com/65220155/134712065-7a5dbccf-9c4b-4338-83b1-294970bd274f.png">

In pages with a different alignment, the pagination would be left-aligned, according to the page's grid:

<img width="963" alt="Captura de ecrã 2021-09-24, às 17 50 06" src="https://user-images.githubusercontent.com/65220155/134712115-94c43bce-6b82-4873-95eb-99bf85894f73.png">
