### ISSUE TITLE
Release category archive should display all releases

### ISSUE THREAD

**Issue by desrosj** [WordPress/wporg-news-2021#259]
The [release category archive](https://wordpress.org/news/category/releases/) archive page in the past has displayed the entire list of releases. When this page is paginated, it's really difficult to find the post for a specific release because of pagination.

[Additional context from a previous ticket on Meta Trac](https://meta.trac.wordpress.org/ticket/5311).

**Comment by coreymckrill** [comment]
This probably just requires changing the `posts_per_page` programmatically for this particular category archive. The page would be super long, though it wouldn't grow very fast. I wonder if we even need to show the post excerpts for this particular category archive...

Thoughts on this, @beafialho?

**Comment by beafialho** [comment]
The Releases archive page as a similar appearance to the Events category. Even though it's not currently implemented that way, the design intention is to only show the excerpt for the latest post, while others only show the post title. This will reduce the space taken by each post and make it possible to increase the number of posts we show in each page.

<img width="783" alt="Captura de ecrã 2022-01-31, às 11 25 05" src="https://user-images.githubusercontent.com/65220155/151785729-61ca8812-a334-4081-9c17-89fbfac32fa8.png">

<img width="483" alt="Captura de ecrã 2022-01-31, às 11 31 46" src="https://user-images.githubusercontent.com/65220155/151787072-72e75e8e-c24b-471d-af83-f99772787d58.png">

Through the posts navigation in the end of the page, it's possible to:
- Navigate the releases chronologically
- Easily jump to the older releases, also quickly accessing the middle ones

Ultimately, if you're looking for a specific release, you can type it in Search.

This doesn't contemplate seeing a list of all the releases but if that's something that ends up being needed for a specific purpose, we can definitely come back to this and iterate on it post launch.

**Comment by desrosj** [comment]
There are [currently over 350 release posts on the blog](https://web.archive.org/web/20220108005354/https://wordpress.org/news/category/releases/), so I definitely wouldn't advocate for listing the posts. In the old design the posts were shown in a table, which worked well. But if the goal is to avoid tables, date and title linking to the post are the most important items here. 

What about showing the most recent release post in an expanded fashion like 5.7.1 in the example above, and then listing all releases in a table below?

The Releases archive essentially serves as an index of all releases. Displaying all of the releases at once makes it easy to scan for the release date of a specific version, to check several versions to find a feature or change that you're looking for, etc.. I realize that I'm a more active contributor, but I reference this list weekly, and several times a month to research or find information I need.

**Comment by jasmussen** [comment]
Congrats on the redesign, just saw it landing, it's incredible! 

The releases page is beautiful, and in particular I love the collapsed style. I also hear the feedback on having to browse between multiple pages. I wonder if the simplest starting point isn't to run with @coreymckrill's suggestion [here](https://github.com/WordPress/wporg-news-2021/issues/259#issuecomment-1024702506), to increase the posts-per-page. For example if there are 350 releases, if we increase the posts-per-page to 100, you'd have 4 pages, conveniently categorizing the archive into a spectrum of new to old, so if you need to read up on release 0.8 you can click Page 4 and go there.

If that also turns out to be insufficient, we can revisit and add a table, for example after collapsed 10 posts. It would be a extra dev work, though, so seems simplest to start with the increased posts per page.

**Comment by beafialho** [comment]
Thank you @jasmussen!

> If that also turns out to be insufficient, we can revisit and add a table, for example after collapsed 10 posts. It would be a extra dev work, though, so seems simplest to start with the increased posts per page.

I agree with @coreymckrill's suggestion to increase posts per page and revisit if needed in the future.
