### ISSUE TITLE
Archive pages navigation links improvements

### ISSUE THREAD

**Issue by beafialho** [WordPress/wporg-news-2021#268]
**1.** Currently the navigation links down at the bottom of the archive pages look quite close to the pre-footer section with very tight spacing:

<img width="1063" alt="Captura de ecrã 2022-01-31, às 16 29 39" src="https://user-images.githubusercontent.com/65220155/151833874-5f374469-4242-4f26-9783-59bf90be9908.png">

I attempted to exemplify the intended spacing with the Inspector tool. Here's what I have changed:

<img width="1310" alt="Captura de ecrã 2022-01-31, às 16 27 59" src="https://user-images.githubusercontent.com/65220155/151833863-90338cc0-df3c-4aa2-b54f-e76f70af3f8e.png">

Let me know if that's not clear.

**2.** Another detail is that the `·` dots between the number of pages and "Older Posts" should not be underlined on hover.

https://user-images.githubusercontent.com/65220155/151834531-9fb513bc-2775-4f34-85d5-30197738f031.mp4

**Comment by tellyworth** [comment]
Re the underline on `.`:

The dot is a `::before` content. In theory, this should work:

```css
		&:hover::before {
			text-decoration: none;
		}
```

In practice though it turns out `text-decoration` is a [special case](https://stackoverflow.com/questions/11474780/hoverbefore-text-decoration-none-has-no-effects/11481121#11481121), and you can't disable the underline only for the pseudo-class in this way.

I don't see an easy fix for that. Can we move that specific issue to the post-launch milestone, or is it a blocker for launch?

I have a PR to add shortly that fixes the spacing.

**Comment by beafialho** [comment]
The `dot` is not a blocker for launch.

**Comment by coreymckrill** [comment]
The underline on the `dot` has been moved to #294
