### ISSUE TITLE
Month in WordPress: what's the best logic?

### ISSUE THREAD

**Issue by beafialho** [WordPress/wporg-news-2021#269]
In the Month in WordPress category, when I click the December 2021 post, my expectation is to read the post about December. Instead, it takes me to the post about November. I get that it works this way because it links to _when_ it was posted, but that can be confusing (at least I find it misleading).

Does this make sense to everyone as well and if so, is there a way to change the way these links work?

https://user-images.githubusercontent.com/65220155/151838824-12c41c16-c539-49de-89b0-b3342b968a43.mp4

**Comment by iandunn** [comment]
One idea would be a custom block similar to https://github.com/WordPress/wporg-news-2021/pull/246#discussion_r792776474. It could have a hardcoded array of month names, and the use `str_contains( $post_title ... )` to find the correct one.

If that fails, it could fall back to using the published month.

A regex is another option instead of `str_contains()`, but that seems like it could [get hacky and have poor readability](https://stackoverflow.com/questions/2655476/regex-to-match-month-name-followed-by-year)

**Comment by tellyworth** [comment]
What about making better use of the post timestamp fields? I think it would make sense for the Dec 2021 post to appear within the `/2021/12/` URL structure for example, rather than `/2022/01/`.

**Comment by ryelle** [comment]
> I think it would make sense for the Dec 2021 post to appear within the /2021/12/ URL structure

The posts are all written once the month ends, so they're all posted about a week into the following month. It's already using [the publish date](https://github.com/WordPress/wporg-news-2021/blob/ac06b2393cc8e2f90dfe17a02a379bd06b1f9339/source/wp-content/themes/wporg-news-2021/block-template-parts/content-category-month-in-wordpress.html#L3), which is why they're all a month off.

I think a custom block would be a good idea, also so we can provide better headings to screen reader users (either full post title or month/year)
<img width="312" alt="Screen Shot 2022-02-01 at 10 33 06 AM" src="https://user-images.githubusercontent.com/541093/151998779-cb3e83e2-48e7-495e-88b6-50968b76fa45.png">
