### ISSUE TITLE
Review the Additional Custom CSS present on the news site

### ISSUE THREAD

**Issue by dd32** [WordPress/wporg-news-2021#295]
On WordPress.org/news/ there's a bunch of extra CSS in the Additional CSS customizer functionality, mostly related to specific announcement posts over the years.

We should verify if this CSS conflicts with the new news theme, and/or if it's still required.

Content of the existing CSS for reference: https://gist.github.com/dd32/d948857fe43bb0aa66b2c0965d5289d7

**Comment by dd32** [comment]
This can probably be shifted to post-launch, but wanted others input first.

**Comment by melchoyce** [comment]
I probably wrote the majority of it, on a case-by-case basis. 

A lot of the styles towards the top of the file are fixing up some issues with the theme either not supporting block styles, or overwriting them somehow. Those can probably all be removed since the new theme takes care of all the block styling.

The individual posts might need a bit more review. In some cases, I was just being picky about the design — those styles we can probably get rid of. 

In some other cases though, the CSS is for specific art direction (like that gradient for the 5.8 announcement post) and we'll want to be a little more careful about checking the impact before getting rid of those styles entirely.

Let me know if I can help at all!

**Comment by dd32** [comment]
@melchoyce Thank you for the background!

If you'd like to take a look yourself, there's a button in the admin bar on /news/ that will load the new theme and you can then test using the customizer & the styles (Although if you publish your changes, you'll remove the live styles, but hey, there's a backup in this issue now)

This isn't a pressing issue, and we can probably keep most of the styles in place for now, but documenting it here as like you mention, some of the 'make the theme block compatible' styles probably need to be removed.

**Comment by coreymckrill** [comment]
Since this isn't pressing, moving to the post-launch milestone.

**Comment by StevenDufresne** [comment]
I would just get rid of all of it, run a sanity check and risk some potential hidden but minor awkward layouts. I would rather get a new ticket opened that we could action quickly than carry forward more debt.

**Comment by ryelle** [comment]
I'm going to close this issue — the CSS wasn't ported over, and no one's noticed 😆 

In all seriousness though, the existing CSS was for block compatibility & release post customization. I've spot-checked the release posts, and they seem fine. Some styles are a little awkward — 5.5 wrapped everything in columns, I think as a way of controlling the padding? and 5.3 had a clashing link color I fixed — but I don't think anything else needs attention.

The posts in question, for reference.

- 5.0: https://wordpress.org/news/2018/12/bebo/
- 5.3: https://wordpress.org/news/2019/11/kirk/
- 5.5: https://wordpress.org/news/2020/08/eckstine/
- 5.8: https://wordpress.org/news/2021/07/tatum/
