### ISSUE TITLE
Community category: Long post titles overflow out the top of the post box for some viewport widths

### ISSUE THREAD

**Issue by coreymckrill** [WordPress/wporg-news-2021#300]
On the Community category archive, at some screen widths the post titles start to overflow out the top of their post boxes. Here it is at 960px:

![text-overflow](https://user-images.githubusercontent.com/916023/153487782-d704807e-aabf-4393-b771-37c036e1367e.jpg)

I tooled around with the CSS but couldn't find a good way to truncate the text in a way that looked decent. Maybe scaling the font down a bit more would help, but it seems like there will always be an edge case with a long title that will need to be handled somehow.

cc @beafialho

**Comment by dd32** [comment]
I've been playing with some CSS, and I'm unable to get something reasonable here too.

The largest problem is that the height of these elements isn't known - they're defined based on a percentage (25% width => aspect ratio 1/1 => height as a percentage) which means you can't define a `max-height` to the inner items, as the height of the parent isn't fixed.

The best option I could come up with was something like this, which works at some resolutions, but nearer the lower ends of the breakpoints isn't quite enough to prevent textual overflows.
```
body.category-community .wp-block-post-title a {
	max-height: 5.5em;
	overflow: hidden;
	text-overflow: ellipsis;
	word-wrap: break-word;
}
```

**Comment by beafialho** [comment]
If it helps, we can scale the post title sizes to a minimum of `26px`, but never less than that because there should be a clear contrast in size between Garamond and Inter for clarity. 

Though ideally, these posts should not lose their squared shapes when resizing the window - except on mobile where it's a specific case - that doesn't happen at the moment:

https://user-images.githubusercontent.com/65220155/153621183-0d934ed1-a3d4-4a82-97a2-9babc2b0b48e.mp4

One way it can behave is instead of altering the shapes, if we resize the window to let's say `2560px` wide, it could have 6 squares instead of 4, if we resize the window to `960px`, it could have 3, and so on. Between these, the posts font sizes could scale up or down, according to the viewport. I mocked that up [here](https://www.figma.com/file/O9I8Jl7kaUMTX39LlRGbGO/News-Page?node-id=11811%3A48367).

<img width="1343" alt="Captura de ecrã 2022-02-11, às 15 54 17" src="https://user-images.githubusercontent.com/65220155/153624745-97cd2f32-e95e-4e93-85ca-eb21f4f07bdf.png">

I don't think this is a blocker for launch, but wanted to leave that solution here in case we want to iterate on it later.

**Comment by dd32** [comment]
If we were to drop the percentage sizes, and move to a minimum width/height in px, I think we'd be able to make the text clip with ellipsis.
