### ISSUE TITLE
Add Podcast category to Categories menu

### ISSUE THREAD

**Issue by beafialho** [WordPress/wporg-news-2021#310]
The Podcast link should be included in the Local Nav Bar:

<img width="1499" alt="Captura de ecrã 2022-02-14, às 09 42 31" src="https://user-images.githubusercontent.com/65220155/153839296-fb4d50b7-bb85-4b4a-ada2-66b0613ebea3.png">

**Comment by coreymckrill** [comment]
🤔 It appears that we don't have a "Podcast" category because it's actually a separate post type, rather than a taxonomy. We can probably filter the category list to add a "Podcast" link, like we did for [All Posts](https://github.com/WordPress/wporg-news-2021/pull/284), that would go the post type archive.

**Comment by beafialho** [comment]
If that's possible, let's do that 👍
