### ISSUE TITLE
Implement 404 Page according to the design

### ISSUE THREAD

**Issue by beafialho** [WordPress/wporg-news-2021#311]
[Figma link](https://www.figma.com/file/O9I8Jl7kaUMTX39LlRGbGO/News-Page?node-id=4659%3A15520)

<img width="1106" alt="Captura de ecrã 2022-02-14, às 12 41 04" src="https://user-images.githubusercontent.com/65220155/153866063-3fbdf98e-6248-40a4-9025-3ba0ec477a04.png">

**Comment by iandunn** [comment]
@beafialho , is this intended to be a global 404 for all sites, or just for the News site (and future sites based off it)?

e.g., should the search input search the News site, or all of wordpress.org? Should the homepage link go to w.org or w.org/news?

**Comment by iandunn** [comment]
Should the global footer be hidden on mobile, or was that just an oversight in the mockup?

**Comment by beafialho** [comment]
@iandunn the 404 page is intended to be aligned throughout WordPress.org sites (including [Openverse which is already implemented](https://wordpress.org/openverse/audis)), this one would be just for News. At this point, I'm not sure how much or if styles would change across sites but the structure will always be the same.

> e.g., should the search input search the News site, or all of wordpress.org? Should the homepage link go to w.org or w.org/news?

I believe the search can work as it is right now, unless a better solution comes to mind to you? Maybe it's a good thing to address in future iterations of the header.

> Should the global footer be hidden on mobile, or was that just an oversight in the mockup?

The footer should be there on mobile, that was an oversight.

**Comment by iandunn** [comment]
> the 404 page is intended to be aligned throughout WordPress.org sites 

That will happen automatically as we redesign sites to use [the parent block theme](https://github.com/WordPress/wporg-news-2021/issues/13). If we don't want to wait for that, we could talk about backporting the design to the old themes, but I think that's be a separate ticket.

> search can work as it is right now, unless a better solution comes to mind

Right now it just searches w.org/news, but it's easy to make it search the whole network. It's also easy to switch the link to be the w.org homepage instead of the news homepage.

I guess it could be confusing if the header search is different than the 404 search, but it also seems useful to have a way to search only the News site.  On Openverse the search and homepage link is limited to the OV site. 

It could also be confusing because visitors don't know where the boundaries are between the sites. e.g. "Is w.org/news a separate site from w.org/about?" Maybe the form should explicitly say _what_ will be searched? e.g., "...try searching News posts using the field below"?

**Comment by iandunn** [comment]
> The footer should be there on mobile

Should the local navigation be there too?

> [Openverse which is already implemented](https://wordpress.org/openverse/audis)

Are there any other parts of the new design that are being implemented elsewhere? If so, it's important to know that so that we don't waste time rewriting a separate version from scratch, and also so we can think about how they'll be integrated. 

Openverse is a bit of an outlier though, since the frontend there is Vue, so it's not easy to reuse code between the sites. cc @zackkrida if you have any thoughts

**Comment by zackkrida** [comment]
Yeah, sadly I don't think there's much opportunity for code reuse. Out 404 also has some inconsistencies with the original design and needs a bit of cleanup. It'll perhaps be best for us to wait for the News implementation to be complete, and then adjust ours to match more closely.

If you want to see it in action: https://search-staging.openverse.engineering/dfadgshdgsafsd

**Comment by beafialho** [comment]
> I guess it could be confusing if the header search is different than the 404 search, but it also seems useful to have a way to search only the News site.

I agree it can be confusing at first having two different searches but also think it's useful to be able to search only the site — or _page_, from a user's perception — you're at. Probably a good balance would be to have a "global" search in the header and a "local" search in each site's 404 page. I also think your idea of contextualising in the copy helps. Here's how that would look:

<img width="1223" alt="Captura de ecrã 2022-02-15, às 15 12 43" src="https://user-images.githubusercontent.com/65220155/154091550-f51e8425-1c86-4bc4-8479-6ae929f39cb7.png">

> Should the local navigation be there too?

No, just global header and footer.

> Are there any other parts of the new design that are being implemented elsewhere?

No, News was the first and no other designs have been implemented. Otherwise we would have posted about it and reached out to you.
