### ISSUE TITLE
Categories list: incorrect sorting

### ISSUE THREAD

**Issue by coreymckrill** [WordPress/wporg-news-2021#324]
Somehow the "Interviews" category is sorting to the top of the list, despite it supposedly being alphabetical:

![incorrect-sorting](https://user-images.githubusercontent.com/916023/154326861-f5590ed6-79e7-4c9f-838c-26e9a7613928.jpg)

**Comment by ryelle** [comment]
I just fixed it (inadvertently), it was a content issue — because it had a description, it had a `title` attribute. I think the regex to split the list into an array didn't account for a title after the `href`, so it was not pulled out to be sorted.

It shouldn't have a title attribute anyway (it means that some screen readers would read "Er. Interviews" instead of "Interviews" 😑 ), which is why I removed it in the first place. I also remove the description from "Docs project", but that's a nested category and wasn't visible here anyway.
