### ISSUE TITLE
Homepage latest release doesn't account for betas/RCs

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-news-2021#371]
This makes it look like 6.0 stable is out:
![Screen Shot 2022-04-12 at 4 17 33 PM](https://user-images.githubusercontent.com/484068/163069723-f350764f-6967-4424-b644-bc21f1bd7be1.png)

**Comment by ryelle** [comment]
How should the "real" version be communicated? IMO `Beta` feels too long, compared to `RC`/`5.x`, especially on the releases page. @beafialho What do you think?

<img width="1177" alt="Screen Shot 2022-04-21 at 6 19 29 PM" src="https://user-images.githubusercontent.com/541093/164560880-ca5e1a0a-94ac-44cb-923b-aea59cf03e61.png">

<img width="1632" alt="Screen Shot 2022-04-21 at 6 20 25 PM" src="https://user-images.githubusercontent.com/541093/164560987-cc0ed137-9990-421f-ab3f-48d8f878e7dc.png">

Edit: Looking at it longer, maybe it's fine?

**Comment by beafialho** [comment]
@ryelle yeah, I think it's fine to keep the full word here :+1:

**Comment by ryelle** [comment]
This is deployed now. I also sized down the font a little, since "beta#" collided with the text on mid-sized screens

Before:
![releases-larger-font](https://user-images.githubusercontent.com/541093/164736583-49610477-a4c4-4512-9d39-0de9507de483.png)

After:
![releases-smaller-font](https://user-images.githubusercontent.com/541093/164736585-7539a007-5787-46e3-a104-7b2524d8edef.png)
