### ISSUE TITLE
Post author missing from single template

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-news-2021#376]
https://wordpress.org/news/2022/05/wordpress-6-0-release-candidate-3-rc3-now-available-for-testing/

![Screen Shot 2022-05-17 at 10 49 20 AM](https://user-images.githubusercontent.com/484068/168877823-4503444b-525d-4c1f-82ca-ed7a20925cce.png)

**Comment by desrosj** [comment]
Also came here to report this! Thanks @iandunn.

**Comment by dd32** [comment]
Upstream issue: https://github.com/WordPress/gutenberg/issues/41121

**Comment by dd32** [comment]
To be more specific.

We're using the `wp:post-author-name` block which only exists within Gutenberg.

Gutenberg 13.2.1 (and maybe others?) don't ship with a `navigation-area` block, but it's in the Gutenberg Repo + in the blocks file, Gutenberg returns early (instead of just skipping the single file) when a file doesn't exist, and thus, all of the Gutenberg blocks with a name further in the alphabet than 'navigation-area' aren't loaded when Gutenberg is active.
