### ISSUE TITLE
Remove or Disable Jetpack "Share this Post" feature News Posts

### ISSUE THREAD

**Issue by DanSoschin** [WordPress/wporg-news-2021#408]
I recommend disabling the Jetpack feature for "Share this Post" (as depicted in the attached screenshot). Twitter no longer works, and each news post is amplified manually so that posts go out to not just Twitter and Facebook but often LinkedIn, Instagram, and Pinterest. Therefore, having this feature turned on by default, or even made available, is unnecessary and can be confusing to an author when publishing a post.
<img width="337" alt="Screenshot 2023-10-18 at 2 41 23 PM" src="https://github.com/WordPress/wporg-news-2021/assets/53192304/2614525d-91b6-4160-b885-bd4bdaae87d6">

**Comment by eidolonnight** [comment]
I second this. We've had a few instances in recent weeks where News posts have been redundantly shared. To make matters worse, automatic post text from Jetpack is often not formatted well for social media (not a Jetpack issue but rather a result of how posts are written), and media is either missing or not optimized for each platform.

Since these posts are shared to [the official WordPress social media accounts](https://make.wordpress.org/marketing/handbook/social-media-accounts/) through Sprout, there is no need for this Jetpack feature to be enabled.

**Comment by eidolonnight** [comment]
Just published the [The Month in WordPress – October 2023](https://wordpress.org/news/2023/11/the-month-in-wordpress-october-2023/) and this somehow the auto post happened again. Are we sure this has been completely disconnected/disabled?

**Comment by StevenDufresne** [comment]
Interesting. Can you confirm that you no longer see the options when publishing?

**Comment by eidolonnight** [comment]
![CleanShot 2023-11-13 at 15 28 52@2x](https://github.com/WordPress/wporg-news-2021/assets/115154/6388c6ee-5900-48f4-a0d6-3c503bc181c5)

![CleanShot 2023-11-13 at 15 49 31@2x](https://github.com/WordPress/wporg-news-2021/assets/115154/42018185-6cd7-40a0-b288-bd5c94a02503)

I can confirm that the post-to-Facebook option no longer appears, but every post seems to still trigger automatic posting to Facebook. These posts are definitely coming from Jetpack too, and they are labeled as such.

**Comment by eidolonnight** [comment]
The Facebook account has been disconnected, and I can confirm that the latest News post did not trigger a Facebook auto-post.
