### ISSUE TITLE
Restore "All Posts" header etc

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-news-2021#55]
The "All Posts" header in `index.html` was [temporarily removed](https://github.com/WordPress/wporg-news-2021/pull/41#issuecomment-943828995) in #41

> Noting that there currently isn't a very good way to show the "All Posts" title, which should appear in the Blue Bar on the Posts page if the site is configured to have a static homepage. Ideally we'd use the query-title block since that outputs the category term names when viewing category archives. I suggested that this block should also cover the Posts page title at https://github.com/WordPress/gutenberg/issues/33476#issuecomment-943811086.
>
> The alternative for now, I think, is to copy the header-navigation.html block template part directly into a template specifically for the Posts page view (home.html I think?) and replace the query-title block with a hard-coded "All Posts" heading block.

> On second thought, the "All Posts" heading block could probably live outside the header.html block template part. So the home.html file would be identical to index.html, but with the addition of a heading block above the <main> tag. We'd have to figure https://github.com/WordPress/wporg-news-2021/pull/41/files#r733194398 out first, though.

> Another idea would be to have both query-title and hardcoded All Posts in the template part, but hide one or the other w/ CSS until the G issue is resolved. 

We should figure out the best way to add it back, and the related headers like "News" on the homepage, "Podcast", etc

Related #51

- [x] Restore the markup/styles from #41, but only on search/date/tag/author templates?
- [x] show "all posts", "search: basetrack", "date: 2020", etc based on context

**Comment by iandunn** [comment]
@beafialho, the mockup shows an "all posts / latest posts" screen, but AFAICT the site won't really have anything like that. Latest posts will only be shown on the homepage, which has its own unique mockup.

WP's template hierarchy looks like this:
![image](https://user-images.githubusercontent.com/484068/139126101-c12e71cc-e0d7-4ac8-b379-6111c50224f3.png)

The closest thing to "all posts" are the archives, like:

* Tag - https://wordpress.org/news/tag/design/
* Author - https://wordpress.org/news/author/webcommsat/
* Date - https://wordpress.org/news/2021/

Search also seems to fit (the site-specific search, like https://wordpress.org/news/?s=basetrack, not the global search like https://wordpress.org/search/basetrack).

* Are those the screens you intended to show "All posts" on?
* Should it say "All posts" on each, or be specific to the content (e.g. "All 2020 posts", "all search results", etc)?
* Does what's shown in "All posts" effect what should be shown in the local nav bar? In some cases they may end up saying the same thing, like "News · 2020" in the local nav bar, and then "All 2020 Posts" in the blue bar immediately under it.
    <img width="1282" alt="Screen Shot 2021-10-27 at 11 48 12 AM" src="https://user-images.githubusercontent.com/484068/139128085-86c2ef06-2e5d-4ae4-a549-2e618e0ef81a.png">

**Comment by beafialho** [comment]
> @beafialho, the mockup shows an "all posts / latest posts" screen, but AFAICT the site won't really have anything like that. Latest posts will only be shown on the homepage, which has its own unique mockup.

@iandunn though in the homepage, in the Latest Posts section, if we click in "See all posts" that will take us to the "All Posts" page.

> Are those the screens you intended to show "All posts" on?

"All posts" is meant to show all posts from all categories, shown from the latest post date to the oldest, similar to what we have in News today. That's why I've named it All/Latest Posts.

> Should it say "All posts" on each, or be specific to the content (e.g. "All 2020 posts", "all search results", etc)?

I've added those mockups [here](https://www.figma.com/file/O9I8Jl7kaUMTX39LlRGbGO/News-Page?node-id=8580%3A35909). Here's what I had in mind for search results, tag, author and date:

<img width="1153" alt="Captura de ecrã 2021-10-28, às 09 41 52" src="https://user-images.githubusercontent.com/65220155/139220164-fd2ddc8b-25f2-404d-8b3c-b948c4ff0afb.png">

<img width="1153" alt="Captura de ecrã 2021-10-28, às 09 41 52" src="https://user-images.githubusercontent.com/65220155/139221816-f055e112-5aaa-4bea-aa1f-be9ec4b08ea1.png">

For long terms, such as the author example above, it should adjust font size in a way that it shows the entire term.

> Does what's shown in "All posts" effect what should be shown in the local nav bar? In some cases they may end up saying the same thing, like "News · 2020" in the local nav bar, and then "All 2020 Posts" in the blue bar immediately under it.

The blue nav bar should only show the categories, "All Posts" being one of them:

<img width="335" alt="Captura de ecrã 2021-10-28, às 09 53 45" src="https://user-images.githubusercontent.com/65220155/139222310-a90c889a-9662-4ee2-8bbb-bb44a2187356.png">

Is this helpful? Let me know if more details or mockups are needed.

**Comment by iandunn** [comment]
>  if we click in "See all posts" that will take us to the "All Posts" page.

Ah, ok, I see what you mean. Thanks!

That won't work the way it's currently setup, because of some [limitations in Gutenberg](https://github.com/WordPress/gutenberg/issues/32939), but I can probably figure out a different way to set it up and get a similar result.


> I've added [date/tag/search] mockups here.

It seems like `i7` in Figma is now the final version for the screens it contains, and the "final" sections are final for the screens that don't show up in `i7`?

Is `i6` also more final than "final"? I've been working off the "final" section, so there could be lots of things that were done to outdated specs.

Regardless, I worry `i7` is going to create confusion, especially if other developers come on for drive-by contributions. What do you think about putting all the final stuff in the section labeled "final", or some other way to have all the final stuff in one place?

**Comment by iandunn** [comment]
> Here's what I had in mind for search results, tag, author and date:

That looks good 👍🏻 

Do you want other screens to also apply that design, like categories? Currently many of them have the "breadcrumb" ( in local nav, like https://www.figma.com/file/O9I8Jl7kaUMTX39LlRGbGO/News-Page?node-id=4852%3A36290

By "breadcrumb" i mean "Date: 2020" when you're looking at 2020 date archives, "Community" when you're looking at the community category, "Search: basetrack" on the search page, etc.

I'm referring to the left side of the local nav bar ("News * Community"), not the right side.

Another difference is that sometimes they have the type prefix ("Search: backtrack") and sometimes they don't ("Releases" instead of "Category: Releases")

If it's not consistent across sections, that's going to increase the time to implement it. consistency also seems like better UX IMO.



> "All Posts" being one of them

I don't think Gutenberg's Category block will do that, but I'll see if there's a reasonable workaround.

**Comment by beafialho** [comment]
> Regardless, I worry i7 is going to create confusion, especially if other developers come on for drive-by contributions. What do you think about putting all the final stuff in the section labeled "final", or some other way to have all the final stuff in one place?

You're right! Apologies for the confusion. I'll move everything final to the "Final" page.

> Do you want other screens to also apply that design, like categories? Currently many of them have the "breadcrumb" ( in local nav, like https://www.figma.com/file/O9I8Jl7kaUMTX39LlRGbGO/News-Page?node-id=4852%3A36290

I think we should only see the breadcrumbs for categories. The key thing here is categories look differently than other taxonomies in the News site. That local nav bar is only about categories, that's why I don't think it makes sense to have it described as "Category: Releases", it feels redundant.

> If it's not consistent across sections, that's going to increase the time to implement it.

How much longer/harder will that be in this case?

> I don't think Gutenberg's Category block will do that, but I'll see if there's a reasonable workaround.

Thank you!
