### ISSUE TITLE
`wpcredits` shortcode styled with one username per line

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-news-2021#87]
Visit https://wordpress.org/news-test/2021/07/20/tatum/, change the viewport to at least `1280px`, and scroll down to `This release is the reflection of the hard work of 530 generous volunteer contributors.`

The list of usernames is breaking to a new line, because of how it interacts with the grid layout.

Unfortunately, the shortcode doesn't wrap the output in a parent element, and it wouldn't be practical to edit old posts to add that in `post_content`. We may be able to add one to the shortcode itself without impacting old sites. The code lives in `api.w.org/core/credits`

Or we may be able to tweak the grid CSS to account for this use case.

**Comment by MaggieCabrera** [comment]
I think it makes more sense to wrap the contents of the shortcode into a paragraph tag. I don't see how we can work around this with CSS, since there's nothing we can target (the comas are flying around because they are not wrapped in any tag, they are direct descendants of the grid element).

I couldn't get the shortcode to work on my local install though, and I'm not sure how to best set my local env to work with api.w.org in order to submit a patch for the shortcode, do you know what's the best way to do this?

**Comment by iandunn** [comment]
Yeah, I agree about wrapping in a `p`. I'm planning to test to make sure that won't have any unintended side-effects, and then push it today.

I added a stub for the shortcode in 7c6aa8b. It's not worth trying to connect the real code.
